parameters:
    locale: 'en'
    app.notifications.email_sender: anonymous@example.com

services:
    _defaults:
        autowire: true 
        autoconfigure: true
        bind:
            array $enabledLocales: '%kernel.enabled_locales%'
            string $defaultLocale: '%locale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
